/**
 * Generated by @openapi-codegen
 *
 * @version 1.0.0
 */
export type InvalidInputJSON = {
  message: "Credit card input invalid.";
};

export type IsValidBody = {
  /**
   * @example 5011054488597827
   */
  creditCard: string;
};
